### ISSUE TITLE
We need a logo

### ISSUE THREAD

**Issue by Joezo** [jackdcrawford/five#210]
as a maintainer i need a logo
so that i can buy five stickers

**Comment by shackpank** [comment]
it's got to be something like this, right?

![fullsizerender](https://cloud.githubusercontent.com/assets/655660/9156439/1e343620-3ed2-11e5-8754-4120aaa4a18e.jpg)

**Comment by stuartgiles** [comment]
Couple of options...
![five-logo-ideas](https://cloud.githubusercontent.com/assets/400087/9176862/9586b582-3f85-11e5-87ae-47548c0988e4.png)

5e :+1:

**Comment by lukefrake** [comment]
Aweaome! - 5g or 5h for me!

**Comment by jodiedoubleday** [comment]
5g

**Comment by LouisPryer** [comment]
5g :+1:

**Comment by andrewcashmore** [comment]
5g

**Comment by cameronviner** [comment]
5g

**Comment by kevinhodges** [comment]
5g

**Comment by hx-markterry** [comment]
5g or 5h

**Comment by pmcnr-hx** [comment]
5g / 5h

**Comment by jackdcrawford** [comment]
![](https://slack-files.com/files-pri-safe/T024G0R1J-F0A3RG56W/unofficial_five_js_logo.svg?c=1441285400-a2db2c975057b524ea1bc7403b7b77034cd37f01)

**Comment by paparomeo** [comment]
I recommend https://hexi.pics/ for the stickers. I met the author at NodeConfEU 2015 and Hexi is amazing! :smile_cat: Oh, and the stickers from Hexi are [standard](https://github.com/terinjokes/StickerConstructorSpec) compliant!

**Comment by pmcnr-hx** [comment]
I recommend [Hexi](https://hexi.pics/) for the stickers. I met the author at NodeConfEU 2015 and Hexi is amazing! :smile_cat: Oh, and the stickers from Hexi are [standard](https://github.com/terinjokes/StickerConstructorSpec) compliant!

**Comment by jackdcrawford** [comment]
5g won \o/
