### ISSUE TITLE
Please add dependencies to get to five.

### ISSUE THREAD

**Issue by rjayako** [jackdcrawford/five#247]
Hey can we get one the following dependencies going as well?

- one
- two
- three
- four

Currently my work is something like this which I think can be streamlined with better dependency support.

```
five() - 4 // 1
five() - 3 // 2
five() - 2 // 3
five() - 1 // 4
```

Thank you for this contribution to the Open source community. This will move the JS community to new heights!

**Comment by shackpank** [comment]
No. I get that it's a stab at the `left-pad` thing, but no.

**Comment by tj-commits** [comment]
[`the-number-one`](https://npmjs.com/the-number-one)
[`two`](https://ghub.io/two)
[`numeric-constant-three`](https://npmjs.com/numeric-constant-three)
[`always-four`](https://npmjs.com/always-four)

these may satisfy your needs.
