### ISSUE TITLE
What's the point of this library..?

### ISSUE THREAD

**Issue by billhsu** [jackdcrawford/five#274]
Sorry I just can't get it why there's a library for this..

**Comment by antoligy** [comment]
I think the README covers this fairly well, though maybe this is a good case for us to increase the amount of and the verbosity of our documentation⸮

> [A library to overcomplicate 5.](https://github.com/jackdcrawford/five/blob/master/README.md#fivejs)

**Comment by billhsu** [comment]
Initially I thought this library was making fun of npm and the left-pad incident.

**Comment by tj-commits** [comment]
Functional programming is awesome, so to be a _true_ functional programmer, then you have to make everything a function. `five` is a function, so it works like that.
